name: Build RPMs

on:
  push:
  schedule:
  - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build_rpms:
    runs-on: ubuntu-latest
    steps:
    - name: Build and push RPMs
      run: |
        mkdir /tmp/options
        echo "---" > /tmp/options/options.yml
        echo "rpm_repository:" >> /tmp/options/options.yml
        echo "  digitalocean_access_token: ${{ secrets.RPM_BUILD_DO_ACCESS_TOKEN }}" >> /tmp/options/options.yml
        echo "  s3_api:" >> /tmp/options/options.yml
        echo "    access_key: ${{ secrets.RPM_BUILD_S3_ACCESS_KEY }}" >> /tmp/options/options.yml
        echo "    secret_key: ${{ secrets.RPM_BUILD_S3_SECRET_KEY }}" >> /tmp/options/options.yml
        docker run -v /tmp/options:/root/OPTIONS:z docker.io/manageiq/rpm_build:latest build --build-type nightly --git-ref ${{ github.ref_name }} --update-rpm-repo
